#!/bin/bash

function pibak {
    if [ -z $1 ]
    then
        cat << EOT
    dumps and gzips a device

    USAGE:
        pibak <device> [<outFile>(./piBak.dd.gz)]
EOT
    else
        sudo dd if="$1" bs=32M status=progress | gzip -c > "${2-./piBak.dd.gz}"
    fi;
}

function pires {
    if [ $# -lt 2 ]
    then
        cat << EOT
    reads a gzip of a device's dd and restores it to the destination device

    USAGE:
        pires <gzipSource> <destDevice> [<blockSize> (32M)]

EOT
        return;
    fi;
    gzipSource="$1"
    destDevice="$2"
    blockSize="${3-32M}"

    sudo gzip -cd "$gzipSource" | dd of="$destDevice" bs="$blockSize" status=progress
}

alias hawtspawt='sudo nmcli device wifi hotspot ssid robenheimer password allthebest ifname wlan0'
alias upgrayeddd='sudo apt update && sudo apt upgrade'
